"""Report generation — Markdown, HTML, and JSON output."""

from __future__ import annotations

import json

from dribik.models import Finding, Graph, Scope, WorkspaceMeta
from dribik.scope import asset_ref, classify
from dribik.scoring import apply_scores, risk_matrix


def _finding_asset(graph: Graph, finding: Finding) -> str:
    node = graph.nodes.get(finding.asset_id)
    if node is None:
        return finding.asset_id
    return asset_ref(node.type, node.data) or finding.asset_id


def _severity_counts(findings: list[Finding]) -> dict[str, int]:
    counts: dict[str, int] = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    return counts


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------
def write_report(
    *,
    meta: WorkspaceMeta,
    graph: Graph,
    scope: Scope,
    findings: list[Finding],
) -> str:
    apply_scores(findings)
    in_scope_f: list[Finding] = []
    oos: list[Finding] = []
    for finding in findings:
        ref = _finding_asset(graph, finding)
        status = classify(scope, ref)
        finding.out_of_scope = status != "allow"
        if finding.out_of_scope:
            oos.append(finding)
        else:
            in_scope_f.append(finding)

    in_scope_f.sort(key=lambda f: f.confidence or 0, reverse=True)
    hosts = [n for n in graph.nodes.values() if n.type == "host"]
    endpoints = [n for n in graph.nodes.values() if n.type == "endpoint"]
    counts = _severity_counts(in_scope_f)

    lines = [
        f"# Assessment Report — {meta.program}",
        "",
        f"_Generated by Dribik {meta.dribik_version} (workspace schema {meta.schema_version})._",
        "",
        "## Executive Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| 🔴 Critical | {counts['critical']} |",
        f"| 🟠 High | {counts['high']} |",
        f"| 🟡 Medium | {counts['medium']} |",
        f"| 🟢 Low | {counts['low']} |",
        f"| ℹ️  Info | {counts['info']} |",
        "",
        "## Scope",
        "",
        f"- Program: {scope.program or meta.program}",
        f"- Allow rules: {len(scope.allow)}",
        f"- Deny rules: {len(scope.deny)}",
        "",
        "## Asset Graph",
        "",
        f"- Hosts: {len(hosts)}",
        f"- Endpoints: {len(endpoints)}",
        f"- Nodes total: {len(graph.nodes)}",
        "",
        "## Findings (In Scope)",
        "",
    ]

    if not in_scope_f:
        lines.append("_None._")
        lines.append("")
    for finding in in_scope_f:
        cvss_str = f"{finding.cvss_score:.1f}" if finding.cvss else "N/A"
        lines.extend([
            f"### [{finding.severity.upper()}] {finding.title}",
            "",
            f"- **ID**: `{finding.id}`",
            f"- **Severity**: {finding.severity}",
            f"- **Type**: {finding.vuln_type}",
            f"- **CVSS Score**: {cvss_str}",
            f"- **Confidence**: {finding.confidence:.2f}" if finding.confidence else "- **Confidence**: N/A",
            f"- **Asset**: `{finding.asset_id}`",
            f"- **CWE**: {finding.cwe_id or 'N/A'}",
            f"- **Validated**: {finding.operator_validated}",
            "",
            f"**Summary**: {finding.summary or '_No summary._'}",
            "",
        ])
        if finding.proof_of_concept:
            lines.extend([
                "**Proof of Concept**:",
                "",
                f"```\n{finding.proof_of_concept}\n```",
                "",
            ])
        if finding.remediation:
            lines.extend([
                f"**Remediation**: {finding.remediation}",
                "",
            ])
        if finding.references:
            lines.append("**References**:")
            for ref in finding.references:
                lines.append(f"- {ref}")
            lines.append("")

    lines.extend(["## Out of Scope (Do Not Pursue)", ""])
    if not oos:
        lines.append("_None flagged._")
        lines.append("")
    else:
        lines.append(
            "These records matched deny rules or matched no allow rule. "
            "Listed so ROE drift is visible."
        )
        lines.append("")
        for finding in oos:
            lines.append(f"- **{finding.title}** (`{finding.id}`) asset `{finding.asset_id}`")
        lines.append("")

    lines.extend([
        "## Disclaimer",
        "",
        "This report is generated from operator-imported inventory and active scan results. "
        "All active scanning was performed under explicit written authorization as recorded in the consent log. "
        "Dribik 0.1.0-beta.",
        "",
    ])
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# JSON report (machine-readable)
# ---------------------------------------------------------------------------
def write_json_report(
    *,
    meta: WorkspaceMeta,
    graph: Graph,
    scope: Scope,
    findings: list[Finding],
) -> str:
    apply_scores(findings)
    hosts = [n.id for n in graph.nodes.values() if n.type == "host"]
    endpoints = [n.data.get("url", n.id) for n in graph.nodes.values() if n.type == "endpoint"]
    counts = _severity_counts(findings)
    matrix = risk_matrix(findings)

    payload = {
        "meta": {
            "program": meta.program,
            "dribik_version": meta.dribik_version,
            "created_at": meta.created_at,
        },
        "summary": counts,
        "risk_matrix": matrix,
        "assets": {
            "hosts": len(hosts),
            "endpoints": len(endpoints),
        },
        "findings": [
            {
                "id": f.id,
                "title": f.title,
                "severity": f.severity,
                "vuln_type": f.vuln_type,
                "cvss_score": f.cvss_score,
                "confidence": f.confidence,
                "asset_id": f.asset_id,
                "cwe_id": f.cwe_id,
                "summary": f.summary,
                "proof_of_concept": f.proof_of_concept,
                "remediation": f.remediation,
                "references": f.references,
                "operator_validated": f.operator_validated,
                "out_of_scope": f.out_of_scope,
                "discovered_at": f.discovered_at,
            }
            for f in findings
        ],
    }
    return json.dumps(payload, indent=2)


# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------
def write_html_report(
    *,
    meta: WorkspaceMeta,
    graph: Graph,
    scope: Scope,
    findings: list[Finding],
) -> str:
    apply_scores(findings)
    in_scope_f: list[Finding] = []
    oos: list[Finding] = []
    for finding in findings:
        ref = _finding_asset(graph, finding)
        status = classify(scope, ref)
        finding.out_of_scope = status != "allow"
        if finding.out_of_scope:
            oos.append(finding)
        else:
            in_scope_f.append(finding)
    in_scope_f.sort(key=lambda f: f.confidence or 0, reverse=True)
    counts = _severity_counts(in_scope_f)

    _SEV_COLOR = {
        "critical": "#b00020",
        "high": "#d45500",
        "medium": "#e6a817",
        "low": "#4a90d9",
        "info": "#7f8c8d",
    }

    def badge(severity: str) -> str:
        color = _SEV_COLOR.get(severity, "#999")
        return (
            f'<span style="background:{color};color:#fff;padding:2px 8px;'
            f'border-radius:3px;font-size:0.8em;font-weight:bold;">'
            f'{severity.upper()}</span>'
        )

    def esc(s: str) -> str:
        return (
            s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace('"', "&quot;")
        )

    finding_html = ""
    for finding in in_scope_f:
        cvss_str = f"{finding.cvss_score:.1f}" if finding.cvss else "N/A"
        refs_html = "".join(
            f'<a href="{esc(r)}" target="_blank">{esc(r)}</a><br>'
            for r in finding.references
        )
        poc_html = f"<pre>{esc(finding.proof_of_concept)}</pre>" if finding.proof_of_concept else ""
        finding_html += f"""
        <details>
          <summary>
            {badge(finding.severity)}
            <strong>{esc(finding.title)}</strong>
            &nbsp;<small>({esc(finding.vuln_type)})</small>
          </summary>
          <div style="padding:12px 16px;border-left:3px solid {_SEV_COLOR.get(finding.severity, '#999')}">
            <table>
              <tr><td><b>ID</b></td><td><code>{esc(finding.id)}</code></td></tr>
              <tr><td><b>CVSS</b></td><td>{cvss_str}</td></tr>
              <tr><td><b>CWE</b></td><td>{esc(finding.cwe_id or 'N/A')}</td></tr>
              <tr><td><b>Asset</b></td><td><code>{esc(finding.asset_id)}</code></td></tr>
              <tr><td><b>Confidence</b></td><td>{f"{finding.confidence:.2f}" if finding.confidence else "N/A"}</td></tr>
            </table>
            <p><b>Summary:</b> {esc(finding.summary)}</p>
            {"<p><b>Proof of Concept:</b></p>" + poc_html if poc_html else ""}
            {"<p><b>Remediation:</b> " + esc(finding.remediation) + "</p>" if finding.remediation else ""}
            {"<p><b>References:</b><br>" + refs_html + "</p>" if refs_html else ""}
          </div>
        </details>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Dribik Report — {esc(meta.program)}</title>
  <style>
    body {{font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
           max-width:960px;margin:0 auto;padding:24px;color:#222;background:#fafafa;}}
    h1 {{border-bottom:2px solid #333;padding-bottom:8px;}}
    h2 {{color:#444;margin-top:32px;}}
    details {{margin:8px 0;background:#fff;border:1px solid #ddd;border-radius:4px;}}
    summary {{cursor:pointer;padding:10px 14px;list-style:none;display:flex;align-items:center;gap:8px;}}
    summary::-webkit-details-marker {{display:none;}}
    table {{border-collapse:collapse;width:100%;margin:8px 0;}}
    td {{padding:4px 8px;border-bottom:1px solid #eee;vertical-align:top;}}
    td:first-child {{width:130px;font-weight:600;color:#555;}}
    code {{background:#f0f0f0;padding:1px 4px;border-radius:3px;font-size:0.9em;}}
    pre {{background:#1e1e1e;color:#d4d4d4;padding:12px;border-radius:4px;overflow-x:auto;font-size:0.85em;}}
    a {{color:#0066cc;}}
    .stat-grid {{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:16px 0;}}
    .stat-card {{text-align:center;padding:16px;border-radius:6px;color:#fff;}}
    .stat-card .num {{font-size:2em;font-weight:bold;}}
    .stat-card .lbl {{font-size:0.8em;opacity:0.9;}}
  </style>
</head>
<body>
  <h1>&#128202; Dribik Report — {esc(meta.program)}</h1>
  <p><em>Generated by Dribik {esc(meta.dribik_version)}</em></p>

  <h2>Executive Summary</h2>
  <div class="stat-grid">
    <div class="stat-card" style="background:#b00020"><div class="num">{counts['critical']}</div><div class="lbl">Critical</div></div>
    <div class="stat-card" style="background:#d45500"><div class="num">{counts['high']}</div><div class="lbl">High</div></div>
    <div class="stat-card" style="background:#e6a817"><div class="num">{counts['medium']}</div><div class="lbl">Medium</div></div>
    <div class="stat-card" style="background:#4a90d9"><div class="num">{counts['low']}</div><div class="lbl">Low</div></div>
    <div class="stat-card" style="background:#7f8c8d"><div class="num">{counts['info']}</div><div class="lbl">Info</div></div>
  </div>

  <h2>Asset Graph</h2>
  <ul>
    <li>Hosts: {len([n for n in graph.nodes.values() if n.type == "host"])}</li>
    <li>Endpoints: {len([n for n in graph.nodes.values() if n.type == "endpoint"])}</li>
    <li>Total nodes: {len(graph.nodes)}</li>
  </ul>

  <h2>Findings ({len(in_scope_f)} in-scope)</h2>
  {finding_html or "<p><em>No in-scope findings.</em></p>"}

  {"<h2>Out of Scope (" + str(len(oos)) + ")</h2><ul>" + "".join(f"<li><b>{esc(f.title)}</b> ({esc(f.id)})</li>" for f in oos) + "</ul>" if oos else ""}

  <hr>
  <p style="color:#999;font-size:0.85em;">
    All active scanning was performed under explicit written authorization.
    Dribik 0.1.0-beta — for authorized use only.
  </p>
</body>
</html>"""
    return html
